### ISSUE TITLE
Why result of deploying the website is not like yours

### ISSUE THREAD

**Issue by ShixiangWang** [songkong/Blog#1]
Hello songkong (@songkong ), 

Thanks for your nice work, my girlfriend really love it. Here I have an issue about deploying the blog website. The result of fork (https://zhouliuyi.github.io/blog/) is not same as yours (http://kongsong.me/blog/ice-bear-jekyll-theme/). Can you tell me why and help me?

**Comment by songkong** [comment]
When you modified the file '_config.yml' or other files, did you run Jekyll in local and was there anything wrong with the localhost site 'http://localhost:4000/'?

**Comment by ShixiangWang** [comment]
@songkong I just clone, push and change name of repository.

**Comment by songkong** [comment]
I watched your repository and found you did have modified '_config.yml' on 27 Dec 2017. Please run Jekyll at local and see if there's anything wrong with your new code.

**Comment by songkong** [comment]
The base url of your site is 'https://zhouliuyi.github.io', but CSS and JS files are at 'https://zhouliuyi.github.io/Blog'. So you need add a parameter like 'url: https://cloudks.github.io/Blog' in '_config.yml' and then modified resources path in 'head.html' like `'<link rel="stylesheet" href="{{ site.url }}/assets/css/main.css>'.` The 'site.url' will load the 'url' in '_config.yml'. I have tried and fixed your problem.

**Comment by ShixiangWang** [comment]
thanks.😬



来自 魅族 PRO 6s



-------- 原始邮件 --------
发件人：Song <notifications@github.com>
时间：周四 2月1日 14:29
收件人：songkong/Blog <Blog@noreply.github.com>
抄送：王诗翔 <wangshx@shanghaitech.edu.cn>,Author <author@noreply.github.com>
主题：Re: [songkong/Blog] Why result of deploying the website is not like yours (#1)


The base url of your site is 'https://zhouliuyi.github.io', but CSS and JS files are at 'https://zhouliuyi.github.io/Blog'. So you need add a parameter like 'url: https://cloudks.github.io/Blog' in '_config.yml' and then modified resources path in 'head.html' like ''. The 'site.url' will load the 'url' in '_config.yml'. I have tried and fixed your problem.

**Comment by souviksaha97** [comment]
Hello @songkong I'm facing a similar issue. My repository is [here](https://github.com/souviksaha97/happy-birthday-utkarsha). I've tried running it on jekyll. The site is building well there. When I commit and push the changes to gh-pages the site looks very bare.

Can you help me out?
